### ISSUE TITLE
Main Program

### ISSUE THREAD

**Issue by limelect** [DevinAIDeveloper/DevinAI-Remote-Administration-Tool#1]
1. Can you make a project out of all the sources?
2. If no can you associate the files with each tools as a list
3.  So that we can build our own
 
To start going into all the sources and making sence out of them will take to
much time so it is usless with all due respect

**Comment by DevinAIDeveloper** [comment]
> 1. Can you make a project out of all the sources?
> 2. If no can you associate the files with each tools as a list
> 3. So that we can build our own
> 
> To start going into all the sources and making sence out of them will take to much time so it is usless with all due respect


Simple You need DzSocket Library,  first learn DzSocket Library, if you haven't,  then start your own project, while going, you can go back and take a look at my project, and learn,  if you don't mind you can copy paste too, there is nothing wrong about it
